/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.graphdb.server;

import com.graphdb.command.CommandExecutor;
import com.graphdb.core.DatabaseOperations;
import com.graphdb.core.GraphDatabase;

import java.util.Scanner;
import java.util.concurrent.CompletableFuture;

public class App {
    public static void main(String[] args) {

        //Initialise services
        Scanner scanner = new Scanner(System.in);
        DatabaseOperations database = new GraphDatabase();
        CommandExecutor executor = new CommandExecutor(database);

        while(true){
            String input = scanner.nextLine().trim();

            if (input.equalsIgnoreCase("exit")) {
                break;
            }

            try {
                CompletableFuture<String> future = executor.executeCommand(input);
                String result = future.join();
                System.out.println(result);

                if (result.contains("ADIOS")) {
                    break;
                }
            } catch (Exception e) {
                System.out.println("Error: " + e.getMessage());
            }
        }
        scanner.close();
    }
}
